### PR TITLE
updates npm, adds scripts to packagejson, remove livereload+connect u…

### PR DESCRIPTION
**Pull request by KasperAndersson**
…ses browsersync instead

### CODE REVIEW

**Comment by grayghostvisuals** [comment]
Can you explain in more depth what the purpose of this commit is?

**Comment by KasperAndersson** [comment]
Having a problem installing this using node 8.9.1, caused by node-sass binary of 3.1.0 is no longer existing on github, so updated the dependencies to the latest versions..

**Comment by grayghostvisuals** [comment]
@KasperAndersson Ok understandable for sure. Gimme a few days to pull this in and make the updates before I finalize this commit. Also is browser-sync better to use these days? Just curious. Appreciate you taking the time with this. Super helpful.

**Comment by KasperAndersson** [comment]
@grayghostvisuals For sure. Livereload didn't work for me, I've been using browser-sync always so I thought why not. I can look into other ways, but I just have a good track record with browser-sync..

**Pull request closed without merging**
